[project]
protostar-version = "0.9.1"
lib-path = "lib"

cairo-path = ["lib/cairo_contracts/src", "lib/cairo_mmr", "lib", "tests"]

[contracts]
Account = ["src/external/Account.cairo"]
FactsRegistry = ["src/FactsRegistry.cairo"]
L1HeadersStore = ["src/L1HeadersStore.cairo"]
L1MessagesProxy = ["src/L1MessagesProxy.cairo"]
L2StateRootsProcessor = ["src/L2StateRootsProcessor.cairo"]
TWAP = ["src/TWAP.cairo"]

[test]
disable-hint-validation = true
