["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
Account = [
    "./src/external/Account.cairo"
]
FactsRegistry = [
    "./src/FactsRegistry.cairo"
]
L1HeadersStore = [
    "./src/L1HeadersStore.cairo"
]
L1MessagesProxy = [
    "./src/L1MessagesProxy.cairo"
]
TWAP = [
    "./src/TWAP.cairo"
]
