[project]
protostar-version = "0.9.1"
lib-path = "lib"

cairo-path = ["lib/cairo_contracts/src", "lib/cairo_mmr", "lib", "tests"]

[contracts]
Account = ["src/external/Account.cairo"]

EvmFactsRegistry = ["src/connections/common/EvmFactsRegistry.cairo"]

EthereumHeadersStore = ["src/connections/ethereum/HeadersStore.cairo"]
EthereumBlockhashesRecipient = ["src/connections/ethereum/BlockhashesRecipient.cairo"]

StarknetStateRootsProcessor = ["src/connections/starknet/StateRootsProcessor.cairo"]

OptimismStateBatchCommitmentRecipient = ["src/connections/optimism/StateBatchCommitmentRecipient.cairo"]



[test]
disable-hint-validation = true
