[package]
name = "herodotus_eth_starknet"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
[dependencies]
starknet = "2.0.1"
cairo_lib = { path = "../cairo_lib" }

[tool.snforge]
exit_first = true

[tool.sncast.dev]
account = "dev"
network = "testnet"
url = "https://starknet-testnet.public.blastapi.io"
